version: '3'

services:

  quicknode:
    container_name: pratir
    ports:
      - 9000:9000
    networks:
      - ergopad-net
    build:
      context: ./
      dockerfile: ./Dockerfile

# this may require cmd: docker network create ergopad-net
networks:
  ergopad-net:
    external: true
