version: '3'

services:

  pratir-api:
    container_name: pratir-api
    image: pratir-backend:latest
    env_file: .env
    ports:
      - 9000:9000
    networks:
      - pratir-net
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
  pratir-db:
    container_name: pratir-db
    env_file: .env
    image: postgres:14
    restart: unless-stopped
    volumes: 
      - postgres_vol:/var/lib/postgresql/data:cached
    ports: 
      - 5445:5432
    networks:
      - pratir-net

volumes:
  postgres_vol:

networks:
  pratir-net:
    driver: bridge
